#!/bin/sh

OUTPUT_DIR=test_output

mkdir $OUTPUT_DIR
if [ $? -ne 0 ]; then
	exit
fi;

for n in {3,5,7,8,9,10,15,20}; do

	mkdir $OUTPUT_DIR/$n

	for i in more_images/*.pgm; do
		i=`basename $i`
		./imEnhance				\
			more_images/$i			\
			$OUTPUT_DIR/$n/$i.mean.pgm	\
			$OUTPUT_DIR/$n/$i.var.pgm	\
			$OUTPUT_DIR/$n/$i.median.pgm	\
			$OUTPUT_DIR/$n/$i.enhanced.pgm	\
			$n
	done
done

