#!/bin/bash
mkdir out
for n in {3,4,5,6,7,8,9,10,20,25,30}; do
	mkdir out/$n
	for i in more_images/*.pgm; do
		echo -n "$n "
		i=`basename $i`
		./imEnhance more_images/$i  out/$n/$i.mean.pgm out/$n/$i.var.pgm out/$n/$i.stddev.pgm out/$n/$i.median.pgm out/$n/$i.enhanced.pgm $n
	done
done

